import DatePickerInput from '../components/common/DatePickerInput';
import { useEffect, useState } from 'react';
import { Accordion, Alert, Badge, Box, Button, Group, Loader, Modal, Paper, Progress, Select, SimpleGrid, Stack, Table, Text, TextInput, Textarea, Title } from '@mantine/core';
import { IconCheck, IconClipboardCheck, IconRefresh } from '@tabler/icons-react';

const DISCIPLINES = ['ELECTRICAL', 'CIVIL', 'STRUCTURAL', 'MECHANICAL', 'WATER / PUMPING', 'SCADA / COMMUNICATION', 'HSE / ENVIRONMENT'];
const READINESS = ['READY', 'CONDITIONAL', 'BLOCKED', 'NOT_APPLICABLE'];
const API = import.meta.env.VITE_API_BASE_URL || '/api';

export default function SEBReadinessConditionsLayout() {
  const [step, setStep] = useState(0); const [seb, setSeb] = useState(localStorage.getItem('seb_id') || ''); const [revision, setRevision] = useState(localStorage.getItem('seb_revision_id') || ''); const [items, setItems] = useState([]); const [groupedItems, setGroupedItems] = useState({}); const [itemsLoading, setItemsLoading] = useState(false); const [itemsError, setItemsError] = useState(''); const [readiness, setReadiness] = useState({}); const [activeFact, setActiveFact] = useState(null); const [factForm, setFactForm] = useState({ discipline_readiness: '', condition: '', required_action: '', owner: '', target_date: '', blocker: '', blocker_reason: '', related_fact_or_gap: '' }); const [savingFact, setSavingFact] = useState(false); const [done, setDone] = useState(false);
  const [baselines, setBaselines] = useState([]); const [baselinesLoading, setBaselinesLoading] = useState(false); const [baselineError, setBaselineError] = useState(''); const [revisions, setRevisions] = useState([]); const [revisionsLoading, setRevisionsLoading] = useState(false); const [revisionError, setRevisionError] = useState(''); const caseId = localStorage.getItem('sia_case_id') || '';
  const grouped = DISCIPLINES.map(name => ({ name, items: groupedItems[name] || [] }));
  const readinessItems = Object.values(groupedItems).flat();
  const allItemsReady = readinessItems.length > 0 && readinessItems.every(item => item.discipline_readiness);
  const steps = ['Select SEB', 'Select reviewed R01', 'Load reviewed items', 'Assess disciplines', 'Complete assessment'];
  const canNext = [!!seb, !!revision, items.length > 0, allItemsReady, true][step];
  const loadBaselines = async () => { if (!caseId) { setBaselineError('No active SIA case was found.'); return; } setBaselinesLoading(true); setBaselineError(''); try { const response = await fetch(`${API}/seb/baselines?sia_case_id=${encodeURIComponent(caseId)}`); if (!response.ok) throw new Error(`Unable to load SEBs (HTTP ${response.status})`); setBaselines(await response.json()); } catch (error) { setBaselineError(error.message); } finally { setBaselinesLoading(false); } };
  const loadRevisions = async () => { if (!seb) return; setRevisionsLoading(true); setRevisionError(''); try { const response = await fetch(`${API}/seb/revisions?seb_id=${encodeURIComponent(seb)}&revision_status=REVIEW_COMPLETED`); if (!response.ok) throw new Error(`Unable to load revisions (HTTP ${response.status})`); setRevisions(await response.json()); } catch (error) { setRevisionError(error.message); } finally { setRevisionsLoading(false); } };
  const loadReviewedItems = async () => { if (!seb || !revision) return; setItemsLoading(true); setItemsError(''); try { const response = await fetch(`${API}/seb/items/reviewed?seb_id=${encodeURIComponent(seb)}&seb_revision_id=${encodeURIComponent(revision)}`); if (!response.ok) throw new Error(`Unable to load SEB items (HTTP ${response.status})`); setItems(await response.json()); } catch (error) { setItems([]); setItemsError(error.message); } finally { setItemsLoading(false); } };
  const loadGroupedItems = async () => { if (!seb || !revision) return; setItemsLoading(true); setItemsError(''); try { const response = await fetch(`${API}/seb/items/reviewed/by-discipline?seb_id=${encodeURIComponent(seb)}&seb_revision_id=${encodeURIComponent(revision)}`); if (!response.ok) throw new Error(`Unable to load discipline groups (HTTP ${response.status})`); setGroupedItems(await response.json()); setStep(3); } catch (error) { setItemsError(error.message); } finally { setItemsLoading(false); } };
  const saveFactReadiness = async () => { if (!activeFact || !factForm.discipline_readiness) return; setSavingFact(true); setItemsError(''); try { const response = await fetch(`${API}/seb/items/${encodeURIComponent(activeFact.id)}/readiness`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(factForm) }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || 'Unable to save fact readiness'); } setGroupedItems(current => Object.fromEntries(Object.entries(current).map(([name, records]) => [name, records.map(item => item.id === activeFact.id ? { ...item, discipline_readiness: factForm.discipline_readiness } : item)]))); setActiveFact(null); setFactForm({ discipline_readiness: '', condition: '', required_action: '', owner: '', target_date: '', blocker: '', blocker_reason: '', related_fact_or_gap: '' }); } catch (error) { setItemsError(error.message); } finally { setSavingFact(false); } };
  const completeReadiness = async () => { if (!allItemsReady) return; setItemsLoading(true); setItemsError(''); try { const response = await fetch(`${API}/seb/revisions/${encodeURIComponent(revision)}/complete-readiness`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ seb_id: seb }) }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.detail || 'Unable to complete readiness assessment'); } setDone(true); setStep(4); } catch (error) { setItemsError(error.message); } finally { setItemsLoading(false); } };
  useEffect(() => { loadBaselines(); }, []);
  useEffect(() => { loadRevisions(); }, [seb]);
  return <Box p={{ base: 'sm', sm: 'lg' }} maw={1200} mx="auto"><Badge color="green" variant="light">SEP</Badge><Title order={2} mt="sm">Readiness & Conditions</Title><Text size="sm" c="dimmed" mt={4}>Assess discipline readiness after R01 engineering review.</Text><Paper withBorder p="md" mt="lg" mb="lg"><Group justify="space-between"><Text fw={700}>Step {step + 1} of 5</Text><Text c="green.8" size="sm">{steps[step]}</Text></Group><Progress value={(step + 1) * 20} color="green" mt="sm" /></Paper><Paper withBorder p={{ base: 'md', sm: 'xl' }}>
    {step === 0 && <Stack><Group justify="space-between"><Title order={3}>1. Select SEB</Title><Button size="xs" variant="subtle" color="green" leftSection={<IconRefresh size={14} />} onClick={loadBaselines} loading={baselinesLoading}>Reload SEBs</Button></Group><Text size="sm" c="dimmed">SEBs for active SIA case: {caseId || 'Not selected'}</Text>{baselinesLoading ? <Group><Loader size="sm" color="green" /><Text size="sm" c="dimmed">Loading SEBs…</Text></Group> : <Select label="SEB ID" placeholder={caseId ? 'Select SEB' : 'Select an SIA case first'} data={baselines.map(item => ({ value: item.id, label: `${item.seb_code || item.id} · ${item.status || 'DRAFT'}` }))} value={seb || null} onChange={value => { setSeb(value || ''); localStorage.setItem('seb_id', value || ''); setRevision(''); localStorage.removeItem('seb_revision_id'); }} searchable clearable disabled={!caseId} />}{baselineError && <Alert color="red">{baselineError}</Alert>}{!baselinesLoading && caseId && !baselineError && !baselines.length && <Alert color="yellow">No SEBs are available for this SIA case.</Alert>}</Stack>}
    {step === 1 && <Stack><Group justify="space-between"><Title order={3}>2. Select reviewed revision R01</Title><Button size="xs" variant="subtle" color="green" leftSection={<IconRefresh size={14} />} onClick={loadRevisions} loading={revisionsLoading}>Reload revisions</Button></Group><Text size="sm" c="dimmed">Only R01 revisions with REVIEW_COMPLETED are available.</Text>{revisionsLoading ? <Group><Loader size="sm" color="green" /><Text size="sm" c="dimmed">Loading reviewed revisions…</Text></Group> : <Select label="Reviewed R01 revision ID" placeholder={seb ? 'Select reviewed R01 revision' : 'Select an SEB first'} data={revisions.filter(item => item.revision_no === 'R01').map(item => ({ value: item.id, label: `${item.revision_no} · ${item.revision_status}` }))} value={revision || null} onChange={value => { setRevision(value || ''); localStorage.setItem('seb_revision_id', value || ''); }} searchable clearable disabled={!seb} />}{revisionError && <Alert color="red">{revisionError}</Alert>}{!revisionsLoading && seb && !revisionError && !revisions.some(item => item.revision_no === 'R01') && <Alert color="yellow">No REVIEW_COMPLETED R01 revision is available for this SEB.</Alert>}</Stack>}
    {step === 2 && <Stack><Group justify="space-between"><Title order={3}>3. Load reviewed SEB items</Title><Button color="green" leftSection={<IconRefresh size={15} />} onClick={loadReviewedItems} loading={itemsLoading}>Load reviewed items</Button></Group><Text size="sm" c="dimmed">Loads review-status items for the selected SEB and reviewed R01 revision.</Text>{itemsLoading && <Group><Loader size="sm" color="green" /><Text size="sm" c="dimmed">Loading SEB items…</Text></Group>}{itemsError && <Alert color="red">{itemsError}</Alert>}{!itemsLoading && !itemsError && items.length > 0 && <><Alert color="green">{items.length} SEB items loaded and grouped by discipline.</Alert><Box style={{ overflowX: 'auto' }}><Table withTableBorder highlightOnHover><Table.Thead><Table.Tr><Table.Th>Fact ID</Table.Th><Table.Th>Collection</Table.Th><Table.Th>SEB ID</Table.Th><Table.Th>Revision ID</Table.Th><Table.Th>Status</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{items.map(item => <Table.Tr key={item.id}><Table.Td><Text size="xs" style={{ fontFamily: 'monospace' }}>{item.fact_id}</Text></Table.Td><Table.Td>{item.fact_collection || '—'}</Table.Td><Table.Td><Text size="xs" style={{ fontFamily: 'monospace' }}>{item.seb_id}</Text></Table.Td><Table.Td><Text size="xs" style={{ fontFamily: 'monospace' }}>{item.seb_revision_id}</Text></Table.Td><Table.Td><Badge color="blue" variant="light">{item.status}</Badge></Table.Td></Table.Tr>)}</Table.Tbody></Table></Box></>}{!itemsLoading && !itemsError && items.length === 0 && <Alert color="yellow">Load reviewed items to continue.</Alert>}</Stack>}
    {step === 3 && <Stack><Group justify="space-between"><Box><Title order={3}>4-8. Discipline readiness assessment</Title><Text size="sm" c="dimmed">Set readiness and record conditions or blockers for each discipline.</Text></Box><Badge color="green">{Object.keys(readiness).length} / {DISCIPLINES.length} assessed</Badge></Group><Accordion variant="separated" multiple>{grouped.map(group => { const state = readiness[group.name] || ''; const accepted = group.items.filter(i => i.decision === 'ACCEPT').length; const conditional = group.items.filter(i => i.decision === 'ACCEPT_WITH_CONDITION').length; const changes = group.items.filter(i => i.decision === 'CHANGE_REQUIRED').length; const rejected = group.items.filter(i => i.decision === 'REJECT').length; return <Accordion.Item key={group.name} value={group.name}><Accordion.Control><Group justify="space-between" pr="sm"><Text fw={600}>{group.name}</Text><Group gap="xs"><Badge color="green" variant="light">{accepted} accepted</Badge><Badge color="orange" variant="light">{conditional + changes} attention</Badge><Badge color="red" variant="light">{rejected} rejected</Badge></Group></Group></Accordion.Control><Accordion.Panel><Stack><Table withTableBorder><Table.Thead><Table.Tr><Table.Th>Fact</Table.Th><Table.Th>Review decision</Table.Th><Table.Th>Readiness</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{group.items.length ? group.items.map(item => <Table.Tr key={item.id}><Table.Td>{item.fact_id}</Table.Td><Table.Td>{item.decision || '—'}</Table.Td><Table.Td><Button size="xs" color="green" variant="light" onClick={() => { setActiveFact(item); setFactForm(current => ({ ...current, discipline_readiness: '' })); }}>Set readiness</Button></Table.Td></Table.Tr>) : <Table.Tr><Table.Td colSpan={2}><Text c="dimmed" size="sm">No reviewed items for this discipline.</Text></Table.Td></Table.Tr>}</Table.Tbody></Table></Stack></Accordion.Panel></Accordion.Item>; })}</Accordion></Stack>}
    {step === 4 && <Stack align="center" py="lg"><IconClipboardCheck size={42} color="#007336" /><Title order={3}>9. Complete readiness assessment</Title><Text c="dimmed" ta="center">R01 will move from REVIEW_COMPLETED to READINESS_COMPLETED when the update API is connected.</Text>{done ? <Alert color="green" title="Readiness completed">All discipline assessments have been recorded in this session.</Alert> : <Button color="green" leftSection={<IconCheck size={16} />} onClick={() => setDone(true)}>Complete readiness assessment</Button>}</Stack>}
    <Modal opened={Boolean(activeFact)} onClose={() => setActiveFact(null)} title={activeFact ? `Set readiness for fact ${activeFact.fact_id}` : 'Set readiness'} size="lg" centered>
      <Stack>
        <Select label="Discipline readiness" placeholder="Select readiness" data={READINESS} value={factForm.discipline_readiness || null} onChange={value => setFactForm(current => ({ ...current, discipline_readiness: value || '' }))} required />
        {factForm.discipline_readiness === 'CONDITIONAL' && <SimpleGrid cols={{ base: 1, md: 2 }}><Textarea label="Condition" value={factForm.condition} onChange={event => { const fieldValue = event.currentTarget.value; setFactForm(current => ({ ...current, condition: fieldValue })); }} required /><Textarea label="Required action" value={factForm.required_action} onChange={event => { const fieldValue = event.currentTarget.value; setFactForm(current => ({ ...current, required_action: fieldValue })); }} required /><TextInput label="Owner" value={factForm.owner} onChange={event => { const fieldValue = event.currentTarget.value; setFactForm(current => ({ ...current, owner: fieldValue })); }} required /><DatePickerInput label="Target date" value={factForm.target_date} onChange={fieldValue => { setFactForm(current => ({ ...current, target_date: fieldValue })); }} required /></SimpleGrid>}
        {factForm.discipline_readiness === 'BLOCKED' && <SimpleGrid cols={{ base: 1, md: 2 }}><Textarea label="Blocker" value={factForm.blocker} onChange={event => { const fieldValue = event.currentTarget.value; setFactForm(current => ({ ...current, blocker: fieldValue })); }} required /><Textarea label="Reason" value={factForm.blocker_reason} onChange={event => { const fieldValue = event.currentTarget.value; setFactForm(current => ({ ...current, blocker_reason: fieldValue })); }} required /><TextInput label="Related fact / gap" value={factForm.related_fact_or_gap} onChange={event => { const fieldValue = event.currentTarget.value; setFactForm(current => ({ ...current, related_fact_or_gap: fieldValue })); }} required /><TextInput label="Owner" value={factForm.owner} onChange={event => { const fieldValue = event.currentTarget.value; setFactForm(current => ({ ...current, owner: fieldValue })); }} required /></SimpleGrid>}
        <Group justify="flex-end"><Button variant="default" onClick={() => setActiveFact(null)}>Cancel</Button><Button color="green" onClick={saveFactReadiness} loading={savingFact} disabled={!factForm.discipline_readiness}>Save readiness</Button></Group>
      </Stack>
    </Modal>
    <Group justify="space-between" mt="xl" pt="lg" style={{ borderTop: '1px solid #e5e7eb' }}><Button variant="default" disabled={step === 0 || itemsLoading} onClick={() => setStep(s => s - 1)}>Back</Button>{step < 4 && <Button color="green" disabled={!canNext || itemsLoading} loading={(step === 2 || step === 3) && itemsLoading} onClick={step === 2 ? loadGroupedItems : step === 3 ? completeReadiness : () => setStep(s => s + 1)}>{step === 2 ? 'Assess disciplines' : step === 3 ? 'Complete readiness' : 'Continue'}</Button>}</Group>
  </Paper></Box>;
}




